### ISSUE TITLE
Please add more attributes in Appearance in autocomplete component such as backdround, foreground, etc 

### ISSUE THREAD

**Issue by thienphuoc86** [anvilistas/anvil-extras#158]
Please add more attributes in Appearance in Tabs such as backdround, foreground, etc

**Comment by s-cork** [comment]
the tabs already have background and foreground. Can you be more specific?

**Comment by thienphuoc86** [comment]
Sorry, Appearance in autocomplete component not Tabs

**Comment by s-cork** [comment]
For the Autocomplete component you can target the suggestions box with roles and some css.
It already has the role `anvil-role-autocompete`.
You could use that in theme.css to change some of the styling.

e.g.

```css
.anvil-component.anvil-role-autocomplete {
   background-color: red;
}
.anvil-component.anvil-role-autocomplete a {
   color: white;
}
.anvil-component.anvil-role-autocomplete a:hover, .anvil-component.anvil-role-autocomplete a.anvil-role-active {
    background-color: blue;
}
```

Does that work for you?
