### ISSUE TITLE
scroll bar in Tabs when select the last tab

### ISSUE THREAD

**Issue by thienphuoc86** [anvilistas/anvil-extras#159]
![image](https://user-images.githubusercontent.com/86188301/134790420-53af5c67-138e-43eb-9c00-582418607354.png)

Please fix it!

**Comment by s-cork** [comment]
Is this at all zoom levels?
Sometimes this sort of thing happens when you're at a zoom level below 100%.

Try the following in your theme.css and see if it fixes it:
```css
.anvil-extras-tabs .tabs {
    overflow-x: hidden !important;
}
```
