### ISSUE TITLE
 Request for Anvil Extras - Tabs: individually colored tabs 

### ISSUE THREAD

**Issue by NerdNL** [anvilistas/anvil-extras#410]
Anvil Extras is very useable! Thanks for that. Nevertheless I have a feature request.
Currently only the background color for all tabs can be set. I would like to have the ability to give an active tab a different color.

**Comment by s-cork** [comment]
how would you feel about a css solution

```css

.anvil-extras-tabs .tabs .tab a.active {
    background-color: hotpink !important;
}

```

And you can do the same thing with a role if you need it to be different for different tabs
